version: '3.6'
services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress-test
    volumes:
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=castornaut.com
      - LETSENCRYPT_HOST=castornaut.com
      - LETSENCRYPT_EMAIL=ilyes.kahoul@castornaut.com
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: wordpress-phpmyadmin
      links:
        - "mysql:mysql"
      environment:
        - VIRTUAL_HOST=castornaut.com
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=castornaut.com
        - LETSENCRYPT_PORT=8080
        - MYSQL_USERNAME=${MYSQL_USER:-root}
        - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-password}
      restart: always
      expose:
        - 80

networks:
  default:
    external:
      name: nginx-proxy
